title = "The Office"
baseURL = "https://pterodactella.github.io/projectB---Social-Graphs-DTU-2021-/"
languageCode = "en-us"
theme = "ananke"




[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "IDK why this doesn't show"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/illustration.png"


[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Goals"
    identifier = "goal"
    url = "/goal/"

[[menu.main]]
    name = "Analysis"
    identifier = "analysis"
    url = "/analysis/"

[[menu.main]]
    name = "Findings"
    identifier = "findings"
    url = "/findings/"